[package]
name = "alrm"
version = "0.1.0"
authors = ["ValleyKnight <ValleyKnight@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify-rust = "4.4.0"
rusty_audio = "1.2.1"
